version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FORWARDER_ADDRESS=${FORWARDER_ADDRESS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - INFURA_RPC_URL=${INFURA_RPC_URL}
    networks:
      - app-network

  contracts:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge